config/routes.rb
Rails.application.routes.draw do

  root 'users#home'
  get '/home/about' => 'users#about'
  get '/users/search' => 'users#search', as: 'search'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
  	member do
  		get :following, :followers
  	end
  end
  resources :books do
  	resources :book_comments, only: [:create, :edit, :update, :destroy]
  	resources :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :book, counter_cache: :favorites_count

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	before_action :set_variables

	def create
		@favorite = Favorite.create(user_id: current_user.id, book_id: params[:book_id])
		@favorites = Favorite.where(book_id: params[:book_id])
		@book.reload
	end

	def destroy
		favorite = Favorite.find_by(user_id: current_user.id, book_id: params[:book_id])
		favorite.destroy
		@favorites = Favorite.where(book_id: params[:book_id])
		@book.reload
	end

	private

	def set_variables
		@book = Book.find(params[:book_id])
	end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_like.html.erb
<% if user_signed_in? %>
  <% unless book.favorite_user(current_user.id).blank? %>
    <li>
      <%= link_to book_favorite_path(book_id: book.id, id: book.favorites[0].id), class: "fav", method: :delete, remote: true do %>
        <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
        <strong class="favorite_counts"><%= book.favorites_count %></strong>
      <% end %>いいね
    </li>
  <% else %>
    <li>
      <%= link_to book_favorites_path(book.id), class: "fav", method: :post, remote: true do %>
        <i class="fa fa-heart-o" aria-hidden="true"></i>
        <strong class="favorite_counts"><%= book.favorites_count %></strong>
      <% end %>いいね
    </li>
  <% end %>
<% else %>
  <% if book.favorites_count > 0 %>
    <li>
      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
      <strong class="favorite_counts"><%= book.favorites_count %></strong>いいね
    </li>
  <% else %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <strong class="favorite_counts"><%= book.favorites_count %></strong>いいね
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#likes_buttons_<%= @book.id %>").html('<%= j (render("favorites/like", book: @book)) %>');

app/views/favorites/destroy.js.erb
$("#likes_buttons_<%= @book.id %>").html('<%= j (render("favorites/like", book: @book)) %>');