config/routes.rb
Rails.application.routes.draw do

  root 'users#home'
  get '/home/about' => 'users#about'
  get '/users/search' => 'users#search', as: 'search'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
  	member do
  		get :following, :followers
  	end
  end
  resources :books do
  	resources :book_comments, only: [:create, :edit, :update, :destroy]
  	resources :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship",dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  attachment :image

  validates :username, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def following?(other_user)
  	relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
  	relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
  	relationships.find_by(followed_id: other_user.id).destroy
  end

  def self.search(search, search_select, search_method)
    if search
      if search_select == 'ユーザー'
        if search_method == '前方一致'
          User.where(['username LIKE ?', "#{search}%"])
        elsif search_method == '後方一致'
          User.where(['username LIKE ?', "%#{search}"])
        elsif search_method == '完全一致'
          User.where(['username LIKE ?', "#{search}"])
        else search_method == '部分一致'
          User.where(['username LIKE ?', "%#{search}%"])
        end
      else
        if search_method == '前方一致'
          User.includes(:books).where(['title LIKE ? OR opinion LIKE ?', "#{search}%", "#{search}%"]).references(:book)
        elsif search_method == '後方一致'
          User.includes(:books).where(['title LIKE ? OR opinion LIKE ?', "%#{search}", "%#{search}"]).references(:book)
        elsif search_method == '完全一致'
          User.includes(:books).where(['title LIKE ? OR opinion LIKE ?', "#{search}", "#{search}"]).references(:book)
        else search_method == '部分一致'
          User.includes(:books).where(['title LIKE ? OR opinion LIKE ?', "%#{search}%", "%#{search}%"]).references(:book)
        end
      end
    else
      User.all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: [:home, :about]

  def home
  end

  def about
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
  	@user = User.find(params[:id])
    @book = Book.new
    @books = Book.all
  end


  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  	  redirect_to user_path(@user.id)
      flash[:notice] = 'You have updated user successfully.'
    else
      render :edit
    end
  end

  def following
    @book = Book.new
    @user = User.find(params[:id])
    @users = @user.followed_users
    render 'show_follow'
  end

  def followers
    @book = Book.new
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def search
    @users = User.search(params[:search], params[:search_select], params[:search_method])
  end


  private

  def user_params
  	params.require(:user).permit(:username, :image, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper

	def current_user?(user)
		user == current_user
	end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
	<%= f.hidden_field :followed_id %>
	<%= f.submit 'Follow', class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_search_book.html.erb
<h2>Books</h2>
	<table class="table">
		<thead>
			<% users.each do |user| %>
				<% user.books.each do |book| %>
				<tr>
					<td>
						<%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %>
					</td>
					<td>
						<%= book.opinion %>
					</td>
				</tr>
				<% end %>
			<% end %>
		</thead>
	</table>

app/views/users/_search_user.html.erb
<h2>Users</h2>
	<table class="table">
		<thead>
			<% users.each do |user| %>
			<tr>
				<td>
					 <%= user.username %>
				</td>
				<td>
					<%= link_to 'Show', user_path(user.id), class: "user_#{user.id}" %>
				</td>
			</tr>
			<% end %>
		</thead>
	</table>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id), method: :delete) do |f| %>
	<%= f.submit 'Unfollow', class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/about.html.erb
<div class="body">
	<div class="container">
		<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
		<ul class="slider">
			<li><%= image_tag 'wc-logo.png', size: '800x300' %></li>
			<li><%= image_tag 'wcc-logo.png', size: '800x30' %></li>
			<li><%= image_tag 'wcp-logo.png', size: '800x300' %></li>
			<li><%= image_tag 'wcw-logo.png', size: '800x300' %></li>
		</ul>
	</div>
</div>

app/views/users/edit.html.erb
<div class="body">
	<div class="container">
		<p class="notice"></p>
        <p><%= flash[:notice] %></p>
		<h2>User info</h2>
		<%= form_for(@user) do |f| %>
			<% if @user.errors.any? %>
              <div id="error_explanation">
                <h3>
                  <%= I18n.t("errors.messages.not_saved",
                             count: @user.errors.count,
                             resource: @user.class.model_name.human.downcase)
                   %>
                </h3>
                <ul>
                  <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
		    <div class="field">
		    	<label for="user_name">Name</label>
		    	<%= f.text_field :username, class: "name" %>
		    </div>
		    <div class="field">
		    	<label for="user_image">Image</label>
		    	<%= f.attachment_field :image, class: "user-edit-form user_image" %>
		    </div>
		    <div class="field">
		    	<label for="user-introduction">Introduction</label>
		    	<%= f.text_area :introduction, class: 'introduction', id: 'user-introduction' %>
		    </div>
		    <div class="actions">
		    	<%= f.submit 'Update User', class: "update-user" %>
		    </div>
		<% end %>
	</div>
</div>

app/views/users/home.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<div class="top-message col-md-offset-3 col-md-6">
				<h1>welcome to<span class="glyphicon glyphicon-book"><strong>Bookers</strong> !!</h1>
					<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
					<p>you can share and exchange your opinions , inpressions , and emotions</p>
					<p> about various books!</p>
				<div class="btn-wrapper">
					<div class="row">
						<p><%= link_to 'Log in', new_user_session_path, class: 'btn btn-info col-xs-10 col-xs-offset-1 sign_in' %></p>
						<p><%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-success col-xs-10 col-xs-offset-1 sign_up'  %></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="body">
	<div class="container">
		<p class="notice"></p>
        <p><%= flash[:notice] %></p>
		<% if @book.errors.any? %>
		  <div id="error_explanation">
		    <h3>
		      <%= I18n.t("errors.messages.not_saved",
		                 count: @book.errors.count,
		                 resource: @book.class.model_name.human.downcase)
		       %>
		    </h3>
		    <ul>
		      <% @book.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>
		<div class="row">
			<%= render 'books/list', book: @book, user: @user %>
			<div class="col-xs-9">
				<h2>Users</h2>
				<table class="table">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<tbody>
						<% @users.each do |user| %>
						<tr>
							<td>
								<%= attachment_image_tag user, :image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
							</td>
							<td>
								 <%= user.username %>
							</td>
							<td>
								<%= link_to 'Show', user_path(user.id), class: "user_#{user.id}" %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/users/search.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<h2>Search</h2>
			<%= form_tag search_path, method: 'get' do %>
				<%= text_field_tag :search, params[:search] %>
				<%= select_tag :search_select, options_for_select([['選択して下さい', '選択して下さい'], ['ユーザー', 'ユーザー'], ['投稿', '投稿']]) %>
				<%= select_tag :search_method, options_for_select([['選択して下さい', '選択して下さい'], ['前方一致', '前方一致'], ['後方一致', '後方一致'], ['完全一致', '完全一致'], ['部分一致', '部分一致']]) %>
				<%= submit_tag 'Search' %>
			<% end %>
			<% if params[:search_select] == 'ユーザー' %>
				<%= render 'search_user', users: @users %>
			<% end %>

			<% if params[:search_select] == '投稿' %>
				<%= render 'search_book', users: @users %>
			<% end %>


			
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="body">
	<div class="container">
		<p class="notice"></p>
        <p><%= flash[:notice] %></p>
		<% if @book.errors.any? %>
		  <div id="error_explanation">
		    <h3>
		      <%= I18n.t("errors.messages.not_saved",
		                 count: @book.errors.count,
		                 resource: @book.class.model_name.human.downcase)
		       %>
		    </h3>
		    <ul>
		      <% @book.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>
		<div class="row">
			<%= render 'books/list', book: @book, user: @user %>
			<div class="col-xs-9">
				<h2>Books</h2>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<tbody>
						<% @user.books.each do |book| %>
						<tr id="ajax-post">
							<td>
								<%= attachment_image_tag @user, :image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
							</td>
							<td>
								 <%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %>
							</td>
							<td>
								<%= book.opinion %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/users/show_follow.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<%= render 'books/list', book: @book, user: @user %>
			<div class="col-xs-9">
				<h2>Following</h2>
				<table class="table">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<tbody>
						<% @user.followed_users.each do |user| %>
							<tr>
								<td>
									<%= attachment_image_tag user, :image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
								</td>
								<td>
									 <%= user.username %>
								</td>
								<td>
									<%= link_to 'Show', user_path(user.id), class: "user_#{user.id}" %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/users/show_follower.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<%= render 'books/list', book: @book, user: @user %>
			<div class="col-xs-9">
				<h2>Followers</h2>
				<table class="table">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<tbody>
						<% @user.followers.each do |user| %>
							<tr>
								<td>
									<%= attachment_image_tag user, :image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
								</td>
								<td>
									 <%= user.username %>
								</td>
								<td>
									<%= link_to 'Show', user_path(user.id), class: "user_#{user.id}" %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>