config/routes.rb
Rails.application.routes.draw do

  root 'users#home'
  get '/home/about' => 'users#about'
  get '/users/search' => 'users#search', as: 'search'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
  	member do
  		get :following, :followers
  	end
  end
  resources :books do
  	resources :book_comments, only: [:create, :edit, :update, :destroy]
  	resources :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	validates :title, presence: true
	validates :opinion, presence: true, length: { maximum: 200 }

	def favorite_user(user_id)
		favorites.find_by(user_id: user_id)
	end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
    @book.user_id = current_user.id
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @bookn = Book.new
    @comment = BookComment.new
    @comments = BookComment.all
  end

  def create
    #books = Book.allはrender :indexをするとindexアクションを経由せずビューに行くから必要
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = @book.user
    @books = Book.all
    respond_to do |format|
      if @book.save
        format.html
        format.js
      else
        format.js {render :index}
      end
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to book_path(book.id)
      flash[:notice] = 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :opinion)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<td>
	 <%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %>
</td>
<td>
	<%= book.opinion %>
</td>

app/views/books/_index.html.erb
<%= render 'book', book: @book %>

app/views/books/_list.html.erb
<div class="col-xs-3">
	<h2>User info</h2>
	<table class="table">
		<tr><%= attachment_image_tag user, :image, format: 'jpeg', fallback: "/images/no_image.jpg", size: "100x100" %>
			<% unless current_user?(user) %>
				<% if current_user.following?(user) %>
					<%= render 'users/unfollow' %>
				<% else %>
					<%= render 'users/follow' %>
				<% end %>
			<% end %>
		</tr>
		<tr>
			<th>name</th>
			<th><%= user.username %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<% @user ||= current_user %>
			<th>
				<%= link_to following_user_path(user) do %>
					<%= @user.followed_users.count %><br> following
				<% end %>
			</th>
			<th>
				<%= link_to followers_user_path(user) do %>
					<%= user.followers.count %><br> followers
				<% end %>
			</th>
		</tr>
	</table>
	<div class="row">
		<%= link_to '', edit_user_path(user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	</div>
	<h2>New book</h2>
	<%= form_for book, remote: true do |f| %>
		<div class="field row">
			<label for="book_title">Title</label><br>
			<%= f.text_field :title, class: "book_title" %>
		</div>
		<div class="field row">
			<label for="book_opinion">Opinion</label><br>
			<%= f.text_area :opinion, class: "book_body" %>
		</div>
		<div class="actions row">
			<%= f.submit 'Create Book', class: 'btn btn-primary col-xs-12', id: 'button' %>
		</div>
	<% end %>
</div>

app/views/books/create.js.erb
$('#ajax-post').prepend("<%= j (render 'index') %>");

app/views/books/edit.html.erb
<div class="body">
	<div class="container">
          <p class="notice"></p>
          <p><%= flash[:notice] %></p>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<h1>Editing Book</h1>
                    <% if @book.errors.any? %>
                      <div id="error_explanation">
                        <h3>
                          <%= I18n.t("errors.messages.not_saved",
                                     count: @book.errors.count,
                                     resource: @book.class.model_name.human.downcase)
                           %>
                        </h3>
                        <ul>
                          <% @book.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>
				<%= form_for(@book) do |f| %>
                    <div class="field row">
                    	<label for="book_title">Title</label>
                    	<%= f.text_field :title, class: "col-xs-12 book_title" %>
                    </div>
                    <div class="field row">
                    	<label for="book_opinion">Opinion</label>
                    	<%= f.text_area :opinion, class: "col-xs-12 book_body" %>
                    </div>
                    <div class="action row">
                    	<%= f.submit 'Update Book',class: "btn btn-primary col-xs-12" %>
                    </div>
				<% end %>
				<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> | <%= link_to 'Back', books_path, class: "back" %>
			</div>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="body">
	<div class="container">
		<p class="notice"></p>
    	<p><%= flash[:notice] %></p>
		<% if @book.errors.any? %>
		  <div id="error_explanation">
		    <h3>
		      <%= I18n.t("errors.messages.not_saved",
		                 count: @book.errors.count,
		                 resource: @book.class.model_name.human.downcase)
		       %>
		    </h3>
		    <ul>
		      <% @book.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>
		<div class="row">
			<%= render 'books/list', user: @user, book: @book %>
			<div class="col-xs-9">
				<h2>Books</h2>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<tbody>
						<% @books.each do |book| %>
							<tr id="ajax-post">
						    <td>
									<%= link_to user_path(@user), class: "user_#{@user.id}" do %>
										<%= attachment_image_tag book.user, :image,  size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><br>
										<%= @user.username %>
									<% end %>
									<div id="likes_buttons_<%= book.id %>">
										<%= render 'favorites/like', book: book %>
									</div>
								</td>
								<%= render 'book', book: book, favorites: @favorites %>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="body">
	<div class="container">
		<p class="notice"></p>
        <p><%= flash[:notice] %></p>
		<% if @bookn.errors.any? %>
		  <div id="error_explanation">
		    <h3>
		      <%= I18n.t("errors.messages.not_saved",
		                 count: @bookn.errors.count,
		                 resource: @bookn.class.model_name.human.downcase)
		       %>
		    </h3>
		    <ul>
		      <% @bookn.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>
		<div class="row">
			<%= render 'books/list', book: @bookn, user: @user %>
			<div class="col-xs-9">
				<h2>Book detail</h2>
				<table class="table">
					<tr>
						<td>
							<%= link_to user_path(@user), class: "user_#{@user.id}" do %>
								<%= attachment_image_tag @user, :image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
								<%= @user.username %>
							<% end %>
							
						</td>
						<td><%= link_to @book.title, '#', class: "book_#{@book.id}" %></td>
						<td><%= @book.opinion %></td>
					<% if @user.id == current_user.id %>
						<td><%= link_to 'Edit', edit_book_path(@book.id), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to 'Destroy', book_path(@book.id),class: "btn-sm btn-danger destroy_book_#{@book.id}", method: :delete, data: { confirm: '本当に消しますか？'} %></td>
					<% end %>
					</tr>
				</table>
				<h2>Comments</h2>
				<% @book.book_comments.each do |book_comment| %>
					<table class="table">
						<tr>
							<td><%= book_comment.user.username %></td>
							<td><%= book_comment.comment %></td>
							<% if book_comment.user.id == current_user.id %>
								<td>
									<%= link_to 'Edit', edit_book_book_comment_path(@book, book_comment), class: 'btn-sm btn-success' %>
								</td>
								<td>
									<%= link_to 'Destroy', book_path(@book.id), class: 'btn-sm btn-danger', method: :delete, data: { confirm: '本当に消しますか？' } %>
								</td>
							<% end %>
						</tr>
					</table>
				<% end %>
				<h2>New Comment</h2>
					<%= form_for [@book,@comment] do |f| %>
					<div class="field row">
						<label for="book_comment">Comment</label><br>
						<%= f.text_area :comment %>
					</div>
					<div class="actions row">
						<%= f.submit 'Create Comment', class: 'btn btn-primary' %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>