config/routes.rb
Rails.application.routes.draw do

  root 'users#home'
  get '/home/about' => 'users#about'
  get '/users/search' => 'users#search', as: 'search'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
  	member do
  		get :following, :followers
  	end
  end
  resources :books do
  	resources :book_comments, only: [:create, :edit, :update, :destroy]
  	resources :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reroad'  %>
      <link  rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <script src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type="text/javascript"></script>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span>Bookers</span><br>
      </nav>
      <nav class="nav navbar-nav navbar-right">
        <ul>
          <li class="glyphicon">
            <%= link_to 'Search', search_path %>
          </li>
          <% if user_signed_in? %>
            <li><%= link_to 'Home', user_path(current_user.id), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to 'Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to 'Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to 'logout', destroy_user_session_path, class: 'glyphicon glyphicon-log-out logout', method: :delete %></li>
          <% else %>
            <li><%= link_to 'Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to 'About', home_about_path, class: 'glyphicon glyphicon-home about' %></li>
            <li><%= link_to 'sign up', new_user_registration_path, class: 'glyphicon glyphicon-home sign_up' %></li>
            <li><%= link_to 'login', new_user_session_path, class: 'glyphicon glyphicon-home sign_in' %></li>
          <% end %>
        </ul>
      </nav>
    </div>
    </header>
    <%= yield %>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>